source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'async_Example', :exclusive => true do
  pod "async", :path => "../"
end

target 'async_Tests', :exclusive => true do
  pod "async", :path => "../"

  
end
